#server:
#  port: ${SERVER_PORT:8080}
#
#spring:
#  datasource:
#    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD:4999}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    generate-ddl: true

server:
  port: 8080

spring:
  datasource:
#    url: jdbc:postgresql://dpg-ckfa706afg7c7398q4tg-a.oregon-postgres.render.com/database_b32w
#    username: database_b32w_user
#    password: uF65wyZmRpSIN9a7jp80d76yPdIxp1EK
    url: jdbc:postgresql://localhost:5432/auto_service
    username: postgres
    password: 4999
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10KB
      max-file-size: 10MB
      max-request-size: 15MB

jwt:
  access:
    token:
      expiry: 3600000 # 60 minutes
      secret:
        key: b748d7c3b729cc093ecf71aa6a84a7a2e56aa3ade350ff34cc9d9f902c32b173

  refresh:
    token:
      expiry: 864000000 # 10 days
      secret:
        key: