version: "3.8"

services:
  app:
    image: auto-service
    container_name: auto-service
    build: ../
    ports:
      - "8080:8081"
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: 1234

  db:
    container_name: auto-service-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - pg_data:/var/lib/postgresql/auto-service

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5252:5050"

volumes:
  pg_data:
